version: '3'

services:
  faas_gateway:
    build: ./faas_gateway
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./faas_gateway/:/go/src/docker-compose-test/faas_gateway/
    working_dir: /go/src/docker-compose-test/faas_gateway/src

  function-1:
    image: golang:alpine
    labels:
      - "function.name=/sumarize"
      - "function.port=8081"
      - "function.hostname=function-1"
    volumes:
      - ./function-1:/go/src/docker-compose-test/function-1
    working_dir: /go/src/docker-compose-test/function-1/src
    command: go run app.go

  function-2:
    image: golang:alpine
    labels:
      - "function.name=/returnip"
      - "function.port=8082"
      - "function.hostname=function-2"
    volumes:
      - ./function-2:/go/src/docker-compose-test/function-2
    working_dir: /go/src/docker-compose-test/function-2/src
    command: go run app.go
